TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.3 # maximum velocity in x direction
  min_vel_x: 0.02 

  max_vel_theta:  0.3
  min_vel_theta: -0.3
  min_in_place_vel_theta: 0.1

  acc_lim_x: 5.0 # acceleration in x direction
  acc_lim_y: 0.0
  acc_lim_theta: 4.0
  
  escape_vel: -0.2

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.10

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 8
  vx_samples: 18
  vtheta_samples: 18
  sim_granularity: 0.01
