global_costmap:
  global_frame: map 
  robot_base_frame: base_footprint

  update_frequency: 50.0
  publish_frequency: 50.0
  transform_tolerance: 0.5

  static_map: true # whether using an entire static map to initialize the costmap
  resolution: 0.025
