CFLAGS= -Wall -Werror -std=gnu++98 -pedantic -ggdb3

all: cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4

cyoa-step1:   cyoa-step1.cpp cyoa.hpp
	g++ $(CFLAGS) -o cyoa-step1 cyoa-step1.cpp cyoa.cpp
cyoa-step2:   cyoa-step2.cpp cyoa.hpp
	g++ $(CFLAGS) -o cyoa-step2 cyoa-step2.cpp cyoa.cpp
cyoa-step3:   cyoa-step3.cpp cyoa.hpp
	g++ $(CFLAGS) -o cyoa-step3 cyoa-step3.cpp cyoa.cpp
cyoa-step4:   cyoa-step4.cpp cyoa.hpp
	g++ $(CFLAGS) -o cyoa-step4 cyoa-step4.cpp cyoa.cpp

