# Generated by Django 4.1.7 on 2023-04-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pkg',
            fields=[
                ('pkgid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('whid', models.IntegerField(default=0)),
                ('destx', models.IntegerField(default=0)),
                ('desty', models.IntegerField(default=0)),
                ('item', models.CharField(default='Apple', max_length=256)),
                ('truckid', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
                ('evaluation', models.CharField(blank=True, choices=[('excellent', 'excellent'), ('mediocre', 'mediocre'), ('disappointing', 'disappointing')], default='none', max_length=256, null=True)),
            ],
            options={
                'db_table': 'pkg',
            },
        ),
        migrations.CreateModel(
            name='userr',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userr',
            },
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='truckID',
            new_name='truckid',
        ),
        migrations.AlterModelTable(
            name='truck',
            table='truck',
        ),
    ]
